In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(
    np.hstack([np.random.rand(100, 3), np.random.rand(100, 1)]),
    columns=['feature1', 'feature2', 'feature3', 'target']
)

In [34]:
df['target'] = (df['target'] > 0.5).astype(int)

In [35]:
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values.reshape(-1, 1)

In [36]:
x

array([[0.6084998 , 0.50058345, 0.26157576],
       [0.89549574, 0.62729329, 0.83902782],
       [0.78891753, 0.88508422, 0.23454256],
       [0.80598954, 0.37967041, 0.33139915],
       [0.07144789, 0.30169648, 0.46065329],
       [0.86575393, 0.6325412 , 0.56266179],
       [0.9259534 , 0.76546849, 0.02400478],
       [0.35061835, 0.94816246, 0.07820367],
       [0.6230225 , 0.42038334, 0.97267252],
       [0.7261086 , 0.05622409, 0.2133981 ],
       [0.70518382, 0.96416313, 0.66603128],
       [0.9178384 , 0.72111184, 0.68454648],
       [0.5466486 , 0.22854469, 0.32942708],
       [0.25086364, 0.44212589, 0.6603598 ],
       [0.06880268, 0.60504431, 0.68544437],
       [0.441331  , 0.7683073 , 0.56239687],
       [0.4896893 , 0.08686153, 0.3244446 ],
       [0.09525708, 0.77778951, 0.87254931],
       [0.25525041, 0.85022605, 0.44204308],
       [0.34493317, 0.70904584, 0.98954274],
       [0.92159286, 0.18554376, 0.5175266 ],
       [0.35633815, 0.66270614, 0.97772916],
       [0.

In [37]:
y

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    

In [38]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
def preprocessing(x, y):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

    scaler = StandardScaler()
    x_train = scaler.fit_transform(x_train)
    x_test = scaler.transform(x_test)

    return x_train, x_test, y_train, y_test

In [39]:
x_train, x_test, y_train, y_test = preprocessing(x, y)
x_train, x_test, y_train, y_test

(array([[ 1.36425935, -0.25650096, -1.54692322],
        [ 0.15170634, -1.56325377,  1.28331971],
        [-1.86692486, -0.8044865 , -0.89317636],
        [ 0.4125642 ,  1.32409203, -1.39593427],
        [-0.89901775, -0.80305135,  1.18141249],
        [-0.38585926,  0.97050164,  0.06380321],
        [ 0.35134078, -1.68810002,  0.76938318],
        [-1.49662718, -1.41172209, -0.85806038],
        [ 0.64432241, -1.82486652, -1.09982997],
        [-0.9067042 ,  1.11761364, -0.34992675],
        [ 1.3379041 ,  0.78523022,  0.47107493],
        [ 1.33697758, -1.0795552 , -0.30273906],
        [ 0.65469942, -0.74910237,  0.73630231],
        [-0.81494561,  1.05904247,  0.20844302],
        [ 1.29206995,  0.50935973,  0.58121202],
        [ 1.14948876,  0.43753553,  0.06468648],
        [-1.60685275, -0.93826984, -1.09113474],
        [ 1.37209345, -1.2136691 ,  0.99308564],
        [ 0.93037657,  1.04740666,  1.02406877],
        [-0.2109233 , -1.70459558, -0.72957826],
        [ 0.55966431

In [40]:
weights = np.random.rand(x_train.shape[1])
bias = 0

In [41]:
def sigmoid(x, weights, bias):
    z = np.dot(x, weights) + bias
    return 1 / (1 + np.exp(-z))

In [42]:
def loss(y_true, y_pred):
    m = y_true.shape[0]
    y_pred = y_pred.reshape(-1, 1)
    return - (1/m) * np.sum(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

In [43]:
def compute_gradients(x_train, y_train, weights, bias):
    m = x_train.shape[0]
    y_pred = sigmoid(x_train, weights, bias).reshape(-1, 1)
    dw = (1/m) * np.dot(x_train.T, (y_pred - y_train))
    db = (1/m) * np.sum(y_pred - y_train)
    return dw, db

In [46]:
def train(x_train, y_train, weights, bias, learning_rate=0.01, epochs=1000):
    for epoch in range(epochs):
        y_pred = sigmoid(x_train, weights, bias).reshape(-1, 1)
        current_loss = loss(y_train, y_pred)
        dw, db = compute_gradients(x_train, y_train, weights, bias)
        weights -= learning_rate * dw.flatten()  # <-- flatten here
        bias -= learning_rate * db
        if epoch % 100 == 0:
            print(f'Epoch {epoch}, Loss: {current_loss}')
    return weights, bias

In [47]:
trained_weights, trained_bias = train(x_train, y_train, weights, bias, learning_rate=0.01, epochs=1000)

Epoch 0, Loss: 0.9379999977490059
Epoch 100, Loss: 0.8487136527096905
Epoch 200, Loss: 0.7830413169859723
Epoch 300, Loss: 0.7376864924326334
Epoch 400, Loss: 0.7079866856925477
Epoch 500, Loss: 0.689256858383042
Epoch 600, Loss: 0.6777031265694174
Epoch 700, Loss: 0.6706481495413865
Epoch 800, Loss: 0.6663511774513204
Epoch 900, Loss: 0.6637295886441817
